In [2]:
import numpy as np

## reshape

#### `ndarray.reshape()`
- converts an existing ndarray into a given shape and size
- passing `-1` as parameter results in dynamic reshape

In [6]:
original_array = np.arange(12)
print("original array:\n", original_array)

reshaped_array = original_array.reshape(3,4) # reshape into 3 rows x 4 columns
print("reshaped array:\n", reshaped_array)

reshaped_array2 = original_array.reshape(6,2) # reshape into 6 rows x 2 columns
print("reshaped array 2:\n", reshaped_array2)

dynamic_reshaped_array = original_array.reshape(-1, 3) # reshape into N rows x 3 columns
print("dynamic reshaped array:\n", dynamic_reshaped_array)

dynamic_reshaped_array2 = original_array.reshape(
    2, -1
)  # reshape into 2 rows x N columns
print("dynamic reshaped array 2:\n", dynamic_reshaped_array2)

original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshaped array 2:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
dynamic reshaped array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
dynamic reshaped array 2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


`reshape(-1,1)` is often used as an intermediary operation  
to match dimensions of different ndarrays before further processing i.e. aggregate functions

In [9]:
array1 = np.arange(8)
array_3d = array1.reshape((2,2,2))
print("array in 3d:\n", array_3d.tolist())

from_3d_to_2d = array_3d.reshape(-1,1)
print("from 3d to 2d:\n", from_3d_to_2d.tolist(), from_3d_to_2d.shape)

from_1d_to_2d = array1.reshape(-1, 1)
print("from 1d to 2d:\n", from_1d_to_2d.tolist(), from_1d_to_2d.shape)

# call some function where ndarrays' dimensions must match

array in 3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
from 3d to 2d:
 [[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
from 1d to 2d:
 [[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
