## first look at numpy


In [1]:
import numpy as np

#### numpy.array()

- input: array-like data
- ouput: ndarray (N-dimensional array)

`array().shape`: shows the dimension and size of the ndarray as a tuple


In [2]:
array1 = np.array([1, 2, 3])
print("array1:", type(array1), array1.shape)
# (3,) => 1 dimensional data, consisting of 3 elements

array2 = np.array([[1, 2, 3], [3, 4, 5]])
print("array2:", type(array2), array2.shape)
# (2, 3) => 2 dimensional data, consisting of 2 rows and 3 columns

array3 = np.array([[1, 2, 3]])
print("array3:", type(array3), array3.shape)
# (1, 3) => 2 dimensional data, consisting of 1 row and 3 columns

array4 = np.array([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
print("array4:", type(array4), array4.shape)
# (2, 2, 3) => 3 dimensional data, consisting of 2 depths, 2 rows and 3 columns

array1: <class 'numpy.ndarray'> (3,)
array2: <class 'numpy.ndarray'> (2, 3)
array3: <class 'numpy.ndarray'> (1, 3)
array4: <class 'numpy.ndarray'> (2, 2, 3)


`ndarray.ndim`

- returns the dimensions of the ndarray


In [3]:
print(
    "array1: {:0} dimension\narray2: {:1} dimension\narray3: {:2} dimension\narray4: {:3} dimension".format(
        array1.ndim, array2.ndim, array3.ndim, array4.ndim
    )
)

array1: 1 dimension
array2: 2 dimension
array3:  2 dimension
array4:   3 dimension


`ndarray.dtype`

- returns the data type of the elements in the ndarray
- all elements in an ndarray must be of the same data type


In [6]:
list1 = [1, 2, 3]
print(type(list1))

arrayFromList1 = np.array(list1)
print(type(arrayFromList1))
print(arrayFromList1, arrayFromList1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


creating an ndarray from a list of mixed data type

- results in an ndarray of larger (more comprehensive) data type
- i.e. int32 & float -> float
- i.e. int32 & string -> string


In [9]:
list2 = [1, 2, "test"]
arrayFromList2 = np.array(list2)
print(arrayFromList2, arrayFromList2.dtype)  # becomes string

list3 = [1, 2, 3.1]
arrayFromList3 = np.array(list3)
print(arrayFromList3, arrayFromList3.dtype)  # becomes float

['1' '2' 'test'] <U11
[1.  2.  3.1] float64


`ndarray.astype()`

- explicitly converts data type to the given argument
- often used to remove unnecessary precision for performance
- relevant precision is lost on conversion


In [12]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

array_int1 = array_float.astype("int32")
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.2, 3.3])
array_int2 = array_float1.astype("int32")
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#### ndarray init helpers

numpy.arange()

- similar to python's native `range()` function


In [14]:
sequential_array = np.arange(10)
print(sequential_array, sequential_array.dtype, sequential_array.shape)

sequential_array2 = np.arange(3, 8)
print(sequential_array2, sequential_array2.dtype, sequential_array2.shape)

[0 1 2 3 4 5 6 7 8 9] int32 (10,)
[3 4 5 6 7] int32 (5,)


numpy.zeros()

- input: tuple describing the shape of the ndarray
- output: ndarray with all elements initialised with zero


In [15]:
zero_array = np.zeros((3, 2), dtype="int32")
print(zero_array, zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)


numpy.ones()

- input: tuple describing the shape of the ndarray
- output: ndarray with all elements initialised with one


In [17]:
one_array = np.ones((2, 3))
print(one_array, one_array.dtype, one_array.shape)

[[1. 1. 1.]
 [1. 1. 1.]] float64 (2, 3)
